name: 'Initialize .NET Framework'
description: 'Sets up .NET 9.0 and installs Aspire workload'
inputs:
  aspire:
    description: 'Whether to install Aspire workload'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Add Aspire Workloads
      if: inputs.aspire != ''
      shell: bash
      run: dotnet workload install aspire 