name: 'Initialize Build'
description: 'Initialize a build for a project'

runs:
  using: composite
  steps:
    - name: Initialize root submodules
      shell: bash
      run: git -c submodule.recurse=false submodule update --init
