name: 'Publish NuGet Packages'
description: 'Publish release packages to NuGet.org or preview packages to Github Packages'

inputs:
  version:
    description: 'Version number for the packages'
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish preview version (${{ inputs.version }}) to GitHub Packages
      if: contains(inputs.version, '-')
      shell: bash
      run: |
        dotnet nuget push './src/**/*.nupkg' --api-key ${{ env.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/Hexalith/index.json --skip-duplicate

    - name: Publish release version (${{ inputs.version }}) to NuGet
      if: "!contains(inputs.version, '-')"
      shell: bash
      run: |
        dotnet nuget push './src/**/*.nupkg' --api-key ${{ env.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate --skip-duplicate
