name: 'Publish NuGet Packages'
description: 'Publish release packages to NuGet.org or preview packages to Github Packages'

inputs:
  version:
    description: 'Version number for the packages'
    required: true
  nuget-api-key:
    description: 'NuGet API Key for publishing to NuGet.org'
    required: true
  github-token:
    description: 'GitHub token for publishing to GitHub Packages'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup GitHub Packages Source
      shell: bash
      run: |
        dotnet nuget add source --username USERNAME --password ${{ inputs.github-token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Hexalith/index.json"

    - name: Publish preview version (${{ inputs.version }}) to GitHub Packages
      if: contains(inputs.version, '-')
      shell: bash
      run: |
        dotnet nuget push './src/**/*.nupkg' --api-key ${{ inputs.github-token }} --source github --skip-duplicate

    - name: Publish release version (${{ inputs.version }}) to NuGet
      if: "!contains(inputs.version, '-')"
      shell: bash
      run: |
        dotnet nuget push './src/**/*.nupkg' --api-key ${{ inputs.nuget-api-key }} --source https://api.nuget.org/v3/index.json --skip-duplicate
