name: Create Release
description: Create a release using automatic versionning

runs:
  using: "composite"
  steps:
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        extra_plugins: |
          @semantic-release/git
          @semantic-release/exec
          @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}