name: Create Release
description: Create a release using automatic versionning

runs:
  using: "composite"
  steps:
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/git
          @semantic-release/exec
          @semantic-release/changelog
