name: 'Get Hexalith Version'
description: 'Gets the version from Hexalith.Version.props file and sets it as an environment variable'

inputs:
  version-path:
    description: 'Path to the Hexalith.Version.props file'
    required: false
    default: './Hexalith.Builds/Hexalith.Version.props'
  buildId:
    description: 'Build ID to be added to preview versions'
    required: false
    default: '0'
  buildAttempt:
    description: 'Build attempt number to be added to preview versions'
    required: false
    default: '0'
  ref:
    description: 'Github ref'
    required: false
    default: ''

outputs:
  version:
    description: 'The version extracted from Hexalith.Version.props'
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Get Version
      id: get-version
      shell: pwsh
      run: |
        [xml]$props = Get-Content "${{ inputs.version-path }}"
        $version = $props.Project.PropertyGroup.HexalithVersion
        if (${{ inputs.ref }} -notmatch '^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$') {
          $version = "$version-preview-${{ inputs.buildId }}-${{ inputs.buildAttempt }}"
        }
        echo "version=$version" >> $env:GITHUB_OUTPUT
        echo "VERSION=$version" >> $env:GITHUB_ENV
