name: Commitlint

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  commitlint:
    uses: ./.github/workflows/commitlint.yml
    with:
      pull-request-title: ${{ github.event.pull_request.title }}
