name: Copy common AI instructions file to Cursor, Cline and Github Copilot rules files

on:
  push:
    paths:
      - 'ai-assistant-instructions.md'

jobs:
  copy-instructions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy instructions to target files
        run: |
          mkdir -p .github
          cp ai-assistant-instructions.md .clinerules
          cp ai-assistant-instructions.md .cursorrules
          cp ai-assistant-instructions.md .github/copilot-instructions.md

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .clinerules .cursorrules .github/copilot-instructions.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Sync AI assistant instructions to all rule files"
          git push 